# Generated by Django 3.2.16 on 2023-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
    ]
